version: '3.9'

services:
  main-proxy:
    image: nginx:alpine
    container_name: main-proxy
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./config
        target: /etc/nginx/conf.d